development:
  adapter: postgresql
  database: syck_syck_desenvolvimento
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5

# test:
#   adapter: postgresql
#   database: syck_syck_test
#   username: postgres
#   password: admin
#   host: localhost
#   encoding: UTF8
#   pool: 5

production:
  adapter: postgresql
  database: syck_syck_db
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5
  reconnect: true
