development:
  adapter: postgresql
  database: sick_sick_desenvolvimento
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5

# test:
#   adapter: postgresql
#   database: sick_sick_test
#   username: postgres
#   password: admin
#   host: localhost
#   encoding: UTF8
#   pool: 5

production:
  adapter: postgresql
  database: sick_sick_db
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5
  reconnect: true
